const BusinessData = [
  {
    id: 1,
    name: "Patricia Appiakubi",
    contact: "0531706238",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web1.webp",
    email: "patricia@example.com",
  },
  {
    id: 2,
    name: "Sarah Oppong",
    contact: "0264877669",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web2.webp",
    email: "sarah@example.com",
  },
  {
    id: 3,
    name: "Sandra Aboagye",
    contact: "0538488788",
    business: " ",
    location: "Nyameduase",
    image: "../assets/web3.webp",
    email: "sarah@example.com",
  },
  {
    id: 4,
    name: "Margaret Osei",
    contact: "0549868733",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web4.webp",
    email: "margaret@example.com",
  },
  {
    id: 5,
    name: "Nana Aso Sika venture",
    contact: "0240651721",
    business: "Mini Buses",
    location: "Nyameduase",
    image: "../assets/web5.webp",
    email: "nana@example.com",
  },
  {
    id: 6,
    name: "Augustina Arhin",
    contact: "0549601261",
    business: "Artesanal Trade",
    location: "Nyameduase",
    image: "../assets/web6.webp",
    email: "augustina@example.com",
  },
  {
    id: 7,
    name: "Yaa Konadu",
    contact: "0541452957",
    business: "Artesanal Trade",
    location: "Nyameduase",
    image: "../assets/web7.webp",
    email: "yaa@example.com",
  },
  {
    id: 8,
    name: "Bethel Dubai",
    contact: "0541245957",
    business: "General Merchandise",
    location: "Nyameduase",
    image: "../assets/web8.webp",
    email: "mercy@example.com",
  },
  {
    id: 9,
    name: "Awuraa",
    contact: "0549315418",
    business: "General Merchandise",
    location: "Nyameduase",
    image: "../assets/web9.webp",
    email: "awuraa@example.com",
  },
  {
    id: 10,
    name: "Yummies kitchen",
    contact: "0544193862",
    business: "Resturant",
    location: "Nyameduase",
    image: "../assets/web10.webp",
    email: "rebecca@example.com",
  },
  {
    id: 11,
    name: "Obaa Yaa",
    contact: "0249121292",
    business: "",
    location: "Nyameduase",
    image: "../assets/web11.webp",
    email: "daba@example.com",
  },
  {
    id: 12,
    name: "Kwame Gyasi",
    contact: "0591491715",
    business: "Artesanal Trade",
    location: "Nyameduase",
    image: "../assets/web12.webp",
    email: "kwame@example.com",
  },
  {
    id: 13,
    name: "Angelina Serwaa Acheampong",
    contact: "0248676169",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web13.webp",
    email: "angelina@example.com",
  },
  {
    id: 14,
    name: "Hannah Indomie",
    contact: "0595807215",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web14.webp",
    email: "hannah@example.com",
  },
  {
    id: 15,
    name: "Faustina Kyei",
    contact: "0597033455",
    business: "General Merchandise",
    location: "Nyameduase",
    image: "../assets/web15.webp",
    email: "faustina@example.com",
  },
  {
    id: 16,
    name: "Madam Nancy mini",
    contact: "0249593329",
    business: "Other",
    location: "Nyameduase",
    image: "../assets/web16.webp",
    email: "nancy@example.com",
  },
  {
    id: 17,
    name: "Stephen Acquah",
    contact: "0596472716",
    business: "Artesanal Trade",
    location: "Nyameduase",
    image: "../assets/web17.webp",
    email: "stephen@example.com",
  },
  {
    id: 18,
    name: "Kofi Bookye",
    contact: "0241819538",
    business: "General Merchandise",
    location: "Nyameduase",
    image: "../assets/web18.webp",
    email: "kofi@example.com",
  },
  {
    id: 19,
    name: "AKwasi Agyei Cosmetics",
    contact: "0247103149",
    business: "Cosmetics shop",
    location: "Nyameduase",
    image: "../assets/web19.webp",
    email: "kwasi@example.com",
  },
  {
    id: 20,
    name: "JKB Fashion",
    contact: "0269515733",
    business: "Fashion Shop",
    location: "Nyameduase",
    image: "../assets/web20.webp",
    email: "john@example.com",
  },
  {
    id: 21,
    name: "Ama Antwiwah",
    contact: "0534848898",
    business: "AJK Fashion",
    location: "Nyameduase",
    image: "../assets/web21.webp",
    email: "ama@example.com",
  },
  {
    id: 22,
    name: "Sofia Ellen",
    contact: "0246201058",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web22.webp",
    email: "sofia@example.com",
  },
  {
    id: 23,
    name: "Fatima Bintu",
    contact: "0541062822",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web23.webp",
    email: "fatima@example.com",
  },
  {
    id: 24,
    name: "Fasal Ayuba",
    contact: "0246000026",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web24.webp",
    email: "fasal@example.com",
  },
  {
    id: 25,
    name: "Comfort Nyarko",
    contact: "0557749896",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web25.webp",
    email: "comfort@example.com",
  },
  {
    id: 26,
    name: "God Damsah",
    contact: "0540723126",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web26.webp",
    email: "god@example.com",
  },
  {
    id: 27,
    name: "Gifty Acquah",
    contact: "0249959387",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web27.webp",
    email: "gifty@example.com",
  },
  {
    id: 28,
    name: "Catering Perpetual",
    contact: "0554786461",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web28.webp",
    email: "catering@example.com",
  },
  {
    id: 29,
    name: "Habiba Ramaan",
    contact: "0548708698",
    business: "Sowah’s Appingal",
    location: "Nyameduase",
    image: "../assets/web29.webp",
    email: "habiba@example.com",
  },
  {
    id: 30,
    name: "Fatima Ventures",
    contact: "0504078205",
    business: "Fatima Ventures",
    location: "Nyameduase",
    image: "../assets/web30.webp",
    email: "fatima@example.com",
  },
  {
    id: 31,
    name: "Hamza Yusuf",
    contact: "0244256745",
    business: "Fatima Ventures",
    location: "Nyameduase",
    image: "../assets/web31.webp",
    email: "hamza@example.com",
  },
  {
    id: 32,
    name: "Konadu John",
    contact: "0531476244",
    business: "John lotey",
    location: "Nyameduase",
    image: "../assets/web32.webp",
    email: "konadu@example.com",
  },
  {
    id: 33,
    name: "John lotey",
    contact: "0531476244",
    business: "John lotey",
    location: "Nyameduase",
    image: "../assets/web33.webp",
    email: "john@example.com",
  },
  {
    id: 34,
    name: "Daniela Beauty Salon Mary Mensah",
    contact: "0544235394",
    business: "Daniela Beauty Salon Mary Mensah",
    location: "Nyameduase",
    image: "../assets/web34.webp",
    email: "mary@example.com",
  },
  {
    id: 35,
    name: "Seyoo Hairford",
    contact: "0264037751",
    business: "Seyoo Hairford",
    location: "Nyameduase",
    image: "../assets/web35.webp",
    email: "seyoo@example.com",
  },
];

export default BusinessData;
